package com.example.finalproject.controller;

public enum CommandType {
    SIGN_IN,
    SIGN_OUT,
    CHANGE_LOCALE,
    SIGN_UP,
    SHOW_ALL_ROOMS,
    ADD_ROOM,
    ADD_BUTLER,
    ADD_OWNER,
    DELETE_CLIENT,
    DELETE_BUTLER,
    UPDATE_CASH,
    EDIT_PERSONAL_INFORMATION,
    EDIT_PERSONAL_INFORMATION_ABOUT_CLIENT,
    CREATE_ORDER,
    CHANGE_PASSWORD,
    SELECT_BOOKING_DATES,
    SHOW_BUTLERS_ORDER,
    SHOW_ACTIVE_OR_NOT_ORDERS,
    SHOW_ALL_CLIENTS,
    SHOW_ALL_BUTLERS,
    DEFAULT
}
